trigger:
  - master

pool:
  vmImage: 'macos-latest'

steps:
  - task: Bash@3
    displayName: Create local.properties
    inputs:
      targetType: 'inline'
      script: |
        echo "" >> ./local.properties

  - task: Gradle@2
    displayName: Build
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'assembleLibrary_androidx :library:assembleLibrary :library:test'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      gradleOptions: '-Xmx3072m'
      sonarQubeRunAnalysis: false
